-- supabase/migrations/034_apro_license_catalog.sql
--
-- Apro-Lizenz-Katalog: Hersteller "Apro", Kategorie "Apro-Lizenz",
-- 53 Lizenz-Modelle aus docs/data/apro-lizenzen.xlsx mit EK/VK
-- (einmalig) + EK/VK Softwarepflege (monatlich).
--
-- Erweitert models um drei nullable Spalten:
--   notes (text)                                  - freier Hinweis am Modell
--   default_monthly_update_fee_ek (numeric(10,2)) - monatliche EK-Pflege
--   default_monthly_update_fee_vk (numeric(10,2)) - monatliche VK-Pflege
--
-- Idempotent. Re-Run via NOT EXISTS (UNIQUE-Index auf models enthält
-- nullable version, ON CONFLICT würde Duplikate erlauben).

-- 1) Schema-Erweiterung -------------------------------------------------------
ALTER TABLE models
  ADD COLUMN IF NOT EXISTS notes text,
  ADD COLUMN IF NOT EXISTS default_monthly_update_fee_ek numeric(10,2),
  ADD COLUMN IF NOT EXISTS default_monthly_update_fee_vk numeric(10,2);

-- 2) Hersteller "Apro" --------------------------------------------------------
INSERT INTO manufacturers (name)
VALUES ('Apro')
ON CONFLICT (name) DO NOTHING;

-- 3) Kategorie "Apro-Lizenz" --------------------------------------------------
INSERT INTO categories (name, icon, kind, cluster)
VALUES ('Apro-Lizenz', 'key-round', 'generic', 'sonstiges')
ON CONFLICT (name) DO NOTHING;

-- 4) Lizenz-Modelle seeden ----------------------------------------------------
-- 53 Lizenz-Zeilen aus apro-lizenzen.xlsx
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Kasse  9', 600, 1200, 9, 18, 'pro Kasse' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Kasse  9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Kassenbuch 9', 220, 440, 3.3, 6.6, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Kassenbuch 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Faktura  9', 165, 330, 2.5, 5, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Faktura  9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Gutschein 9', 165, 330, 2.5, 5, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Gutschein 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Office 9', 220, 440, 3.3, 6.6, 'pro Office Pc' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Office 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. FIBU 9', 495, 990, 7.5, 15, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. FIBU 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Lagerstand 9', 550, 1100, 8.3, 16.6, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Lagerstand 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Schank 9', 330, 660, 5, 10, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Schank 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Funk 9', 165, 330, 2.5, 5, 'pro Orderman' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Funk 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Hotelschnittstelle 9', 495, 990, 7.5, 15, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Hotelschnittstelle 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Kredit 9', 165, 330, 2.5, 5, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Kredit 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Waage 9', 330, 660, 5, 10, 'pro Kasse mit Waagenverbund' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Waage 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Bestellmanager 9', 440, 880, 6.6, 13.2, 'pro Bestellmanager' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Bestellmanager 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. WaWi 9', 495, 990, 7.5, 15, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. WaWi 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Card RFID 9', 275, 550, 4.2, 8.4, 'pro Kasse' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Card RFID 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Server 9', 330, 660, 5, 10, 'pro Server' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Server 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Easystart 9', 360, 720, 5.4, 10.8, 'pro Kasse' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Easystart 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Handy 9', 495, 990, 9, 18, 'pro gleichzeitige Nutzung' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Handy 9' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. DATEV_Kassenarchiv', 220, 440, 8.3, 16.6, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. DATEV_Kassenarchiv' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Filialverwaltung', 1045, 2090, 15.7, 31.4, '10,-€ pro Client bei Cloudsynchronisation' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Filialverwaltung' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Lieferando', 440, 880, 6.6, 13.2, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Lieferando' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Delivery Hero', 440, 880, 6.6, 13.2, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Delivery Hero' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Tablex', 440, 880, 6.6, 13.2, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Tablex' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Resmio', 440, 880, 6.6, 13.2, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Resmio' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Tischbestellung', 350, 700, 19.5, 39, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Tischbestellung' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. White Label App', 950, 2500, 9.5, 19, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. White Label App' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Gutschein App', 350, 700, 19.5, 39, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Gutschein App' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Abholung,Zustellung', 350, 700, 19.5, 39, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Abholung,Zustellung' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Kundenanbindung', 350, 700, 19.5, 39, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Kundenanbindung' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Kiosk Software', 1250, 2500, 19.5, 39, 'pro Kiosk' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Kiosk Software' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Digital Payment', 800, 1600, NULL, 0, 'Alle 1,9%, PP 3,4%, +0,35 Transaktionsgebühr' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Digital Payment' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Wallet', 1500, 3000, 19.5, 39, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Wallet' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Digitaler Beleg', 100, 200, 5, 10, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Digitaler Beleg' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Reports', 220, 440, 13, 26, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Reports' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Kasse  10', 600, 1200, 9, 18, 'pro Kasse' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Kasse  10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Kassenbuch 10', 220, 440, 3.3, 6.6, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Kassenbuch 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Faktura  10', 165, 330, 2.5, 5, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Faktura  10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Gutschein 10', 165, 330, 2.5, 5, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Gutschein 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Office 10', 220, 440, 3.3, 6.6, 'pro Office Pc' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Office 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. FIBU 10', 495, 990, 7.5, 15, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. FIBU 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Lagerstand 10', 550, 1100, 8.3, 16.6, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Lagerstand 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Schank 10', 330, 660, 5, 10, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Schank 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Funk 10', 165, 330, 2.5, 5, 'pro Orderman' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Funk 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Hotelschnittstelle 10', 495, 990, 7.5, 15, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Hotelschnittstelle 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Kredit 10', 165, 330, 2.5, 5, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Kredit 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Waage 10', 330, 660, 5, 10, 'pro Kasse mit Waagenverbund' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Waage 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Bestellmanager 10', 440, 880, 6.6, 13.2, 'pro Bestellmanager' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Bestellmanager 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. WaWi 10', 495, 990, 7.5, 15, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. WaWi 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Card RFID 10', 275, 550, 4.2, 8.4, 'pro Kasse' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Card RFID 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. ERP 10', 550, 1100, 8.3, 16.6, 'einmalig pro System' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. ERP 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Server 10', 330, 660, 5, 10, 'pro Server' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Server 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Easystart 10', 360, 720, 5.4, 10.8, 'pro Kasse' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Easystart 10' AND mo.variante IS NULL AND mo.version IS NULL);
INSERT INTO models (manufacturer_id, category_id, modellname, default_ek, default_vk, default_monthly_update_fee_ek, default_monthly_update_fee_vk, notes) SELECT mf.id, c.id, 'APRO. Handy 10', 495, 990, 9, 18, 'pro gleichzeitige Nutzung' FROM manufacturers mf CROSS JOIN categories c WHERE mf.name = 'Apro' AND c.name = 'Apro-Lizenz' AND NOT EXISTS (SELECT 1 FROM models mo WHERE mo.manufacturer_id = mf.id AND mo.modellname = 'APRO. Handy 10' AND mo.variante IS NULL AND mo.version IS NULL);

NOTIFY pgrst, 'reload schema';
